import logging
from pathlib import Path

import pandas as pd

from lib.shared.file_utils import get_filename
from targets.preprocess import get_preprocess_targets

# Get the general configuration options
ROOT_FP = Path(config["all"]["root_fp"])

# Get paths to the sample files dfs
SBS_SAMPLES_FP = Path(config["preprocess"]["sbs_samples_fp"])
PHENOTYPE_SAMPLES_FP = Path(config["preprocess"]["phenotype_samples_fp"])

# load data for samples (this should go into helper function and be stored better)
# Load the sample TSV files with pandas
sbs_samples_df = pd.read_csv(SBS_SAMPLES_FP, sep="\t")
sbs_samples_df = sbs_samples_df.sort_values(by=["well", "tile", "cycle"])
SBS_WELLS = list(sbs_samples_df["well"].unique())
SBS_TILES = list(sbs_samples_df["tile"].unique())
SBS_CYCLES = list(sbs_samples_df["cycle"].unique())
# TODO: unrestrict wells and tiles after testing
SBS_WELLS = ["A1"]
SBS_TILES = [1]

phenotype_samples_df = pd.read_csv(PHENOTYPE_SAMPLES_FP, sep="\t")
phenotype_samples_df = phenotype_samples_df.sort_values(by=["well", "tile"])
PHENOTYPE_WELLS = list(phenotype_samples_df["well"].unique())
PHENOTYPE_TILES = list(phenotype_samples_df["tile"].unique())


include: "rules/preprocess.smk"


if "sbs_process" in config:

    include: "rules/sbs_process.smk"


PREPROCESS_FP = ROOT_FP / "preprocess"
SBS_PROCESS_FP = ROOT_FP / "sbs_process"

PREPROCESS_TARGETS = get_preprocess_targets(
    PREPROCESS_FP,
    SBS_WELLS,
    SBS_TILES,
    SBS_CYCLES,
    PHENOTYPE_WELLS,
    PHENOTYPE_TILES,
)

print(PREPROCESS_TARGETS)


# Define the target files for the workflow
rule all:
    input:
        # preprocessing
        PREPROCESS_TARGETS["extract_metadata_sbs"],
