# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build documentation in the docs/source directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Set the requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .