

# BrieFlow cluster configuration file

default-resources:
    slurm_partition: None
    slurm_account: None
    mem_mb: 2000
    tasks: 1
    cpus_per_task: 1
    runtime: 120
    slurm_extra: "'--output=slurm_output/rule/%j.out'"
jobs: 100

set-resources:
    # preprocessing
    extract_metadata_sbs:
        mem_mb: 500
    extract_metadata_phenotype:
        mem_mb: 500
    convert_sbs:
        mem_mb: 500
    convert_ph:
        mem_mb: 500
    calculate_ic_sbs:
        mem_mb: 10000
    calculate_ic_phenotype:
        mem_mb: 10000
    combine_metadata_sbs:
        mem_mb: 10000
    combine_metadata_phenotype:
        mem_mb: 10000
    # sbs_process
    align:
        mem_mb: 1000
    log_filter:
        mem_mb: 1000
    compute_standard_deviation:
        mem_mb: 1000
    find_peaks:
        mem_mb: 500
    max_filter:
        mem_mb: 750
    apply_ic_field_sbs:
        mem_mb: 1000
    segment_sbs:
        # slurm_partition: "'nvidia-2080ti-20'"
        mem_mb: 3000
        cpus_per_task: 4
        # slurm_extra: "'--gres=gpu:1'"
    extract_bases:
        mem_mb: 750
    call_reads:
        mem_mb: 100
    call_cells:
        mem_mb: 200
    extract_sbs_info:
        mem_mb: 200
    combine_reads:
        mem_mb: 20000
    combine_cells:
        mem_mb: 20000
    combine_sbs_info:
        mem_mb: 20000
    # phenotype_process
    apply_ic_field_phenotype:
        mem_mb: 1000
    segment_phenotype:
        # slurm_partition: "'nvidia-2080ti-20'"
        mem_mb: 3000
        cpus_per_task: 4
        # slurm_extra: "'--gres=gpu:1'"
    identify_cytoplasm:
        mem_mb: 1000
    extract_phenotype_info:
        mem_mb: 200
    merge_phenotype_info:
        mem_mb: 20000
    extract_phenotype_cp:
        mem_mb: 200
    merge_phenotype_cp:
        mem_mb: 20000
    eval_segmentation_phenotype:
        mem_mb: 2000
    eval_features:
        mem_mb: 2000
    